import Head from "next/head";
import Hero from "../components/landingPage/hero";
import ProductExplanation from "../components/landingPage/productExplanation";
import ProductIntro from "../components/landingPage/productIntro";
import QuizSection from "../components/landingPage/quizSection";
import SocialProof from "../components/landingPage/socialProof";
import ValueProposition from "../components/landingPage/valueProposition";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nurture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <ValueProposition />
      <ProductExplanation />
      <SocialProof />
      <QuizSection />
      <ProductIntro />
      <Link href="/quiz?index=0">
        <a>Take quiz</a>
      </Link>
    </>
  );
}
