import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import ChildQuestionOne from "../components/quiz/childQuestionOne";
import ChildQuestionThree from "../components/quiz/childQuestionThree";
import ChildQuestionTwo from "../components/quiz/childQuestionTwo";
import ParentQuestionOne from "../components/quiz/parentQuestionOne";
import ParentQuestionTwo from "../components/quiz/parentQuestionTwo";
import PracticalQuestionOne from "../components/quiz/practicalQuestionOne";
import PracticalQuestionTwo from "../components/quiz/practicalQuestionTwo";
import PreferenceQuestionOne from "../components/quiz/preferenceQuestionOne";
import PreferenceQuestionTwo from "../components/quiz/preferenceQuestionTwo";
import PreferenceQuestionThree from "../components/quiz/preferenceQuestionThree";
import QuizStart from "../components/quiz/quizStart";
import styles from "../styles/Quiz.module.css";
import FinalScreen from "../components/quiz/finalScreen";
import NurseriesList from "../components/quiz/nurseriesList";

const Quiz = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        {router.query.index == "0" && <QuizStart />}
        {router.query.index == "1" && <PracticalQuestionOne />}
        {router.query.index == "2" && <PracticalQuestionTwo />}
        {router.query.index == "3" && <ChildQuestionOne />}
        {router.query.index == "4" && <ChildQuestionTwo />}
        {router.query.index == "5" && <ChildQuestionThree />}
        {router.query.index == "6" && <ParentQuestionOne />}
        {router.query.index == "7" && <ParentQuestionTwo />}
        {router.query.index == "8" && <PreferenceQuestionOne />}
        {router.query.index == "9" && <PreferenceQuestionTwo />}
        {router.query.index == "10" && <PreferenceQuestionThree />}
        {router.query.index == "11" && <FinalScreen />}
        {router.query.index == "12" && <NurseriesList />}
      </div>
    </>
  );
};

export default Quiz;
